set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

fmt:
    test -z "$(gofmt -l .)"

vet:
    go vet ./...
    go -C failsafeown vet ./...
    staticcheck ./...

# Whitespace style: a blank line where a block ends and a new statement group
# begins. Pinned to v5 because v4 bundles an x/tools too old to read Go 1.27
# export data and dies with "package strconv without types". Covers every
# module, since ./... in the root does not reach the submodules.
WSL := "github.com/bombsimon/wsl/v5/cmd/wsl@v5.9.0"

wsl:
    go run {{WSL}} ./...
    go -C failsafeown run {{WSL}} ./...
    go -C analysis run {{WSL}} ./...
    go -C benchmarks run {{WSL}} ./...

# Apply the rules rather than report them. Mechanical, and reviewed as its own
# commit.
wsl-fix:
    go run {{WSL}} -fix ./...
    go -C failsafeown run {{WSL}} -fix ./...
    go -C analysis run {{WSL}} -fix ./...
    go -C benchmarks run {{WSL}} -fix ./...

# Run velocity's own analyzers (lostrelease) as a vet tool over every module.
lint:
    go -C analysis build -o "${TMPDIR:-/tmp}/velocityvet" ./cmd/velocityvet
    go vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...
    go -C benchmarks vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...
    go -C analysis test ./...
    go -C failsafeown vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...

test:
    go test ./...
    go -C failsafeown test ./...

race:
    go test -race ./...
    go -C failsafeown test -race ./...

debug:
    go test -tags=velocitydebug ./...

# The same sequence CI runs; see .github/workflows/ci.yml.
check: fmt vet wsl lint test race debug examples

examples:
    go test ./... -run Example

fuzz duration="30s":
    go test ./ownership -run '^$' -fuzz '^FuzzOwnershipModel$' -fuzztime {{duration}}

bench:
    go test ./... -run '^$' -bench . -benchmem

bench-compare count="5":
    go -C benchmarks test ./... -run '^$' -bench . -benchmem -count={{count}}
