set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

fmt:
    test -z "$(gofmt -l .)"

vet:
    go vet ./...
    go -C failsafeown vet ./...
    staticcheck ./...

# Whitespace style, through golangci-lint's bundled wsl_v5. See .golangci.yml:
# it runs this one linter and nothing else, because the rest of velocity's
# analysis is run directly, each pinned, and adopting a second copy of it is
# duplication with two places to configure the same rule.
#
# Covers every module, since ./... in the root does not reach the submodules.
wsl:
    golangci-lint run ./...
    go -C failsafeown run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run ./...
    go -C analysis run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run ./...
    go -C benchmarks run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run ./...

# Apply the rules rather than report them. Mechanical, and reviewed as its own
# commit.
wsl-fix:
    golangci-lint run --fix ./...
    go -C failsafeown run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run --fix ./...
    go -C analysis run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run --fix ./...
    go -C benchmarks run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run --fix ./...

# Run velocity's own analyzers (lostrelease) as a vet tool over every module.
lint:
    go -C analysis build -o "${TMPDIR:-/tmp}/velocityvet" ./cmd/velocityvet
    go vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...
    go -C benchmarks vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...
    go -C analysis test ./...
    go -C failsafeown vet -vettool="${TMPDIR:-/tmp}/velocityvet" ./...

test:
    go test ./...
    go -C failsafeown test ./...

race:
    go test -race ./...
    go -C failsafeown test -race ./...

debug:
    go test -tags=velocitydebug ./...

# The same sequence CI runs; see .github/workflows/ci.yml.
check: fmt vet wsl lint test race debug examples

examples:
    go test ./... -run Example

fuzz duration="30s":
    go test ./ownership -run '^$' -fuzz '^FuzzOwnershipModel$' -fuzztime {{duration}}

bench:
    go test ./... -run '^$' -bench . -benchmem

bench-compare count="5":
    go -C benchmarks test ./... -run '^$' -bench . -benchmem -count={{count}}
